#!/usr/bin/env python3
"""Stimulate GMail to pull mail from the remote email host more often.
Typically run every 5 minutes by a cron job:
 */5  *  *  *  *  cd /<path to script dir>/ && ./gmailnudge.py >> log.txt 2>&1
Set up a filter in GMail to delete these messages.
"""
__version__ = "V1.0 220131"

#==========================================================
#
#  Chris Nelson, 2018-2022
#
# V1.0 220131  New for funcs3 V1.0
#
# Changes pending
#   
#==========================================================

import sys
import os.path

CONFIG_FILE = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'gmailnudge.cfg')
FUNCS3_MIN_VERSION = 1.0

sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../funcs3/'))   # Useful if funcs3 is placed elsewhere
from funcs3 import SndEmailError, loadconfig, getcfg, logging, snd_email

def main():

    loadconfig(CONFIG_FILE)

    # Set up GMail rule to delete messages with subject = the NudgeText in config file.
    try:
        snd_email (subj=getcfg('NudgeText'), body="Don't care", to='EmailTo', log=True)
        logging.info ('Nudge message sent')         # This log is redundant if log=True on the snd_email call
    except SndEmailError as e:
        logging.error(f"  {e}")
    # except Exception as e:
    #     logging.error(f"Catchall error:\n  {e}")


if __name__ == '__main__':
    main()
