#!/usr/bin/env python3
"""Check WAN IP address and if it has changed then send me an email
See wanstatus for a more complete implementation - https://github.com/cjnaz/wanstatus
"""

__version__ = "V0.6 210512"

#==========================================================
#
#  Chris Nelson, 2018-2020
#
# V0.6 210512  Using import email creds, requires funcs3 0.6 min
# V0.5 201203  funcs3_min_version_check demo.
# V0.4 201028  Bug fix that required cwd == script dir.  Requires Python3.7 minimum (subprocess capture_output).
# V0.3 200426  Changed to curl, updated funcs3 module.
# V0.2 190319  Genericized EmailTo, fixed Python 3x compatibility.
# V0.1 180521  New
#
# Changes pending
#   
#==========================================================


import subprocess
import sys
import os.path


CONFIG_FILE = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'WANIPCheck.cfg')

sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../funcs3/'))   # Useful if funcs3 is placed elsewhere
from funcs3 import *
funcs3_min_version = 0.6


setuplogging()

def main():
    loadconfig(CONFIG_FILE)

    try:
        WANip = subprocess.run(["curl", 'https://ipapi.co/ip/'], capture_output=True, text=True).stdout # .split("\n")
    except Exception as e:
        logging.error ("Getting the WAN IP failed: <{}>".format(e))
        sys.exit (1)

    WANfile = progdir + getcfg('WanIpFile')

    if not os.path.exists(WANfile):
        with open(WANfile, 'w') as ofile:
            ofile.write (WANip)
            logging.warning ("Created {} with IP address {}".format(WANfile, WANip))
        sys.exit ()

    with open(WANfile) as ifile:
        SavedWANip = ifile.readline()

    if WANip != SavedWANip:
        message = "Prior WAN IP: <{}>. Current WAN IP: <{}>".format (SavedWANip, WANip)
        subject = "NOTICE:  HOME WAN IP CHANGED"
        snd_notif (subj=subject, msg=message, log=True)
        snd_email (subj=subject, body=message, to='EmailTo')

        with open(WANfile, 'w') as ofile:
            ofile.write (WANip)
    else: logging.info ("No change")


if __name__ == '__main__':

    if not funcs3_min_version_check(funcs3_min_version):
        logging.error(f"ERROR:  funcs3 module must be at least version {funcs3_min_version}.  Found <{funcs3_version}>.")
        sys.exit(1)

    
    main()
